[package]
name = "baum-c"
version = "0.1.0"
edition = "2021"

[dependencies]
baum-lang = { path = "../baum-lang" }
baum-front = { path = "../baum-front" }
baum-core = { path = "../baum-core" }
baum-rt = { path = "../baum-rt" }
