[package]
name = "baum-ls"
version = "0.1.0"
edition = "2021"

[dependencies]
baum-lang = { path = "../baum-lang" }
lsp-server = "0.7.8"
lsp-types = "0.97.0"
serde_json = "1.0.139"
serde = "1.0.218"
colored = "3.0.0"
ropey = "1.6.1"
